from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField

#User input form for "/daily"
class TickerForm(FlaskForm):
    ticker1 = SelectField("Ticker 1:", choices=[("AAL","AAL"),("AAPL","AAPL"),("ADBE","ADBE"),("ADI","ADI"),("ADP","ADP"),
    ("ADSK","ADSK"),("ALGN","ALGN"),("ALXN","ALXN"),("AMAT","AMAT"),("AMD","AMD"),
    ("AMGN","AMGN"),("AMZN0","AMZN"),("ASML","ASML"),("ATVI","ATVI"),("AVGO","AVGO"),
    ("BIDU","BIDU"),("BIIB","BIIB"),("BKNG","BKNG"),("BMRN","BMRN"),("CDNS","CDNS"),
    ("CELG","CELG"),("CERN","CERN"),("CHKP","CHKP"),("CHTR","CHTR"),("CMCSA","CMCSA"),
    ("COST","COST"),("CSCO","CSCO"),("CSX","CSX"),("CTAS","CTAS"),("CTRP","CTRP"),
    ("CTSH","CTSH"),("CTXS","CTXS"),("DLTR","DLTR"),("EA","EA"),("EBAY","EBAY"),
    ("EXPE","EXPE"),("FAST","FAST"),("FB","FB"),("FISV","FISV"),("FOX","FOX"),
    ("FOXA","FOXA"),("GILD","GILD"),("GOOG","GOOG"),("GOOGL","GOOGL"),("HAS","HAS"),
    ("HSIC","HSIC"),("IDXX","IDXX"),("ILMN","ILMN"),("INCY","INCY"),("INTC","INTC"),
    ("INTU","INTU"),("ISRG","ISRG"),("JBHT","JBHT"),("JD","JD"),("KHC","KHC"),
    ("KLAC","KLAC"),("LBTYA","LBTYA"),("LBTYK","LBTYK"),("LRCX","LRCX"),("LULU","LULU"),
    ("MAR","MAR"),("MCHP","MCHP"),("MDLZ","MDLZ"),("MELI","MELI"),("MNST","MNST"),
    ("MSFT","MSFT"),("MU","MU"),("MXIM","MXIM"),("MYL","MYL"),("NFLX","NFLX"),
    ("NTAP","NTAP"),("NTES","NTES"),("NVDA","NVDA"),("NXPI","NXPI"),("ORLY","ORLY"),
    ("PAYX","PAYX"),("PCAR","PCAR"),("PEP","PEP"),("PYPL","PYPL"),("QCOM","QCOM"),
    ("REGN","REGN"),("ROST","ROST"),("SBUX","SBUX"),("SIRI","SIRI"),("SNPS","SNPS"),
    ("SWKS","SWKS"),("SYMC","SYMC"),("TMUS","TMUS"),("TSLA","TSLA"),("TTWO","TTWO"),
    ("TXN","TXN"),("UAL","UAL"),("ULTA","ULTA"),("VRSK","VRSK"),("VRSN","VRSN"),
    ("VRTX","VRTX"),("WBA","WBA"),("WDAY","WDAY"),("WDC","WDC"),("WLTW","WLTW"),
    ("WYNN","WYNN"),("XEL","XEL"),("XLNX","XLNX")])

    ticker2 = SelectField("Ticker 2:", choices=[("AAL","AAL"),("AAPL","AAPL"),("ADBE","ADBE"),("ADI","ADI"),("ADP","ADP"),
    ("ADSK","ADSK"),("ALGN","ALGN"),("ALXN","ALXN"),("AMAT","AMAT"),("AMD","AMD"),
    ("AMGN","AMGN"),("AMZN0","AMZN"),("ASML","ASML"),("ATVI","ATVI"),("AVGO","AVGO"),
    ("BIDU","BIDU"),("BIIB","BIIB"),("BKNG","BKNG"),("BMRN","BMRN"),("CDNS","CDNS"),
    ("CELG","CELG"),("CERN","CERN"),("CHKP","CHKP"),("CHTR","CHTR"),("CMCSA","CMCSA"),
    ("COST","COST"),("CSCO","CSCO"),("CSX","CSX"),("CTAS","CTAS"),("CTRP","CTRP"),
    ("CTSH","CTSH"),("CTXS","CTXS"),("DLTR","DLTR"),("EA","EA"),("EBAY","EBAY"),
    ("EXPE","EXPE"),("FAST","FAST"),("FB","FB"),("FISV","FISV"),("FOX","FOX"),
    ("FOXA","FOXA"),("GILD","GILD"),("GOOG","GOOG"),("GOOGL","GOOGL"),("HAS","HAS"),
    ("HSIC","HSIC"),("IDXX","IDXX"),("ILMN","ILMN"),("INCY","INCY"),("INTC","INTC"),
    ("INTU","INTU"),("ISRG","ISRG"),("JBHT","JBHT"),("JD","JD"),("KHC","KHC"),
    ("KLAC","KLAC"),("LBTYA","LBTYA"),("LBTYK","LBTYK"),("LRCX","LRCX"),("LULU","LULU"),
    ("MAR","MAR"),("MCHP","MCHP"),("MDLZ","MDLZ"),("MELI","MELI"),("MNST","MNST"),
    ("MSFT","MSFT"),("MU","MU"),("MXIM","MXIM"),("MYL","MYL"),("NFLX","NFLX"),
    ("NTAP","NTAP"),("NTES","NTES"),("NVDA","NVDA"),("NXPI","NXPI"),("ORLY","ORLY"),
    ("PAYX","PAYX"),("PCAR","PCAR"),("PEP","PEP"),("PYPL","PYPL"),("QCOM","QCOM"),
    ("REGN","REGN"),("ROST","ROST"),("SBUX","SBUX"),("SIRI","SIRI"),("SNPS","SNPS"),
    ("SWKS","SWKS"),("SYMC","SYMC"),("TMUS","TMUS"),("TSLA","TSLA"),("TTWO","TTWO"),
    ("TXN","TXN"),("UAL","UAL"),("ULTA","ULTA"),("VRSK","VRSK"),("VRSN","VRSN"),
    ("VRTX","VRTX"),("WBA","WBA"),("WDAY","WDAY"),("WDC","WDC"),("WLTW","WLTW"),
    ("WYNN","WYNN"),("XEL","XEL"),("XLNX","XLNX")])

    ticker3 = SelectField("Ticker 3:", choices=[("AAL","AAL"),("AAPL","AAPL"),("ADBE","ADBE"),("ADI","ADI"),("ADP","ADP"),
    ("ADSK","ADSK"),("ALGN","ALGN"),("ALXN","ALXN"),("AMAT","AMAT"),("AMD","AMD"),
    ("AMGN","AMGN"),("AMZN0","AMZN"),("ASML","ASML"),("ATVI","ATVI"),("AVGO","AVGO"),
    ("BIDU","BIDU"),("BIIB","BIIB"),("BKNG","BKNG"),("BMRN","BMRN"),("CDNS","CDNS"),
    ("CELG","CELG"),("CERN","CERN"),("CHKP","CHKP"),("CHTR","CHTR"),("CMCSA","CMCSA"),
    ("COST","COST"),("CSCO","CSCO"),("CSX","CSX"),("CTAS","CTAS"),("CTRP","CTRP"),
    ("CTSH","CTSH"),("CTXS","CTXS"),("DLTR","DLTR"),("EA","EA"),("EBAY","EBAY"),
    ("EXPE","EXPE"),("FAST","FAST"),("FB","FB"),("FISV","FISV"),("FOX","FOX"),
    ("FOXA","FOXA"),("GILD","GILD"),("GOOG","GOOG"),("GOOGL","GOOGL"),("HAS","HAS"),
    ("HSIC","HSIC"),("IDXX","IDXX"),("ILMN","ILMN"),("INCY","INCY"),("INTC","INTC"),
    ("INTU","INTU"),("ISRG","ISRG"),("JBHT","JBHT"),("JD","JD"),("KHC","KHC"),
    ("KLAC","KLAC"),("LBTYA","LBTYA"),("LBTYK","LBTYK"),("LRCX","LRCX"),("LULU","LULU"),
    ("MAR","MAR"),("MCHP","MCHP"),("MDLZ","MDLZ"),("MELI","MELI"),("MNST","MNST"),
    ("MSFT","MSFT"),("MU","MU"),("MXIM","MXIM"),("MYL","MYL"),("NFLX","NFLX"),
    ("NTAP","NTAP"),("NTES","NTES"),("NVDA","NVDA"),("NXPI","NXPI"),("ORLY","ORLY"),
    ("PAYX","PAYX"),("PCAR","PCAR"),("PEP","PEP"),("PYPL","PYPL"),("QCOM","QCOM"),
    ("REGN","REGN"),("ROST","ROST"),("SBUX","SBUX"),("SIRI","SIRI"),("SNPS","SNPS"),
    ("SWKS","SWKS"),("SYMC","SYMC"),("TMUS","TMUS"),("TSLA","TSLA"),("TTWO","TTWO"),
    ("TXN","TXN"),("UAL","UAL"),("ULTA","ULTA"),("VRSK","VRSK"),("VRSN","VRSN"),
    ("VRTX","VRTX"),("WBA","WBA"),("WDAY","WDAY"),("WDC","WDC"),("WLTW","WLTW"),
    ("WYNN","WYNN"),("XEL","XEL"),("XLNX","XLNX")])

    ticker4 = SelectField("Ticker 4:", choices=[("AAL","AAL"),("AAPL","AAPL"),("ADBE","ADBE"),("ADI","ADI"),("ADP","ADP"),
    ("ADSK","ADSK"),("ALGN","ALGN"),("ALXN","ALXN"),("AMAT","AMAT"),("AMD","AMD"),
    ("AMGN","AMGN"),("AMZN0","AMZN"),("ASML","ASML"),("ATVI","ATVI"),("AVGO","AVGO"),
    ("BIDU","BIDU"),("BIIB","BIIB"),("BKNG","BKNG"),("BMRN","BMRN"),("CDNS","CDNS"),
    ("CELG","CELG"),("CERN","CERN"),("CHKP","CHKP"),("CHTR","CHTR"),("CMCSA","CMCSA"),
    ("COST","COST"),("CSCO","CSCO"),("CSX","CSX"),("CTAS","CTAS"),("CTRP","CTRP"),
    ("CTSH","CTSH"),("CTXS","CTXS"),("DLTR","DLTR"),("EA","EA"),("EBAY","EBAY"),
    ("EXPE","EXPE"),("FAST","FAST"),("FB","FB"),("FISV","FISV"),("FOX","FOX"),
    ("FOXA","FOXA"),("GILD","GILD"),("GOOG","GOOG"),("GOOGL","GOOGL"),("HAS","HAS"),
    ("HSIC","HSIC"),("IDXX","IDXX"),("ILMN","ILMN"),("INCY","INCY"),("INTC","INTC"),
    ("INTU","INTU"),("ISRG","ISRG"),("JBHT","JBHT"),("JD","JD"),("KHC","KHC"),
    ("KLAC","KLAC"),("LBTYA","LBTYA"),("LBTYK","LBTYK"),("LRCX","LRCX"),("LULU","LULU"),
    ("MAR","MAR"),("MCHP","MCHP"),("MDLZ","MDLZ"),("MELI","MELI"),("MNST","MNST"),
    ("MSFT","MSFT"),("MU","MU"),("MXIM","MXIM"),("MYL","MYL"),("NFLX","NFLX"),
    ("NTAP","NTAP"),("NTES","NTES"),("NVDA","NVDA"),("NXPI","NXPI"),("ORLY","ORLY"),
    ("PAYX","PAYX"),("PCAR","PCAR"),("PEP","PEP"),("PYPL","PYPL"),("QCOM","QCOM"),
    ("REGN","REGN"),("ROST","ROST"),("SBUX","SBUX"),("SIRI","SIRI"),("SNPS","SNPS"),
    ("SWKS","SWKS"),("SYMC","SYMC"),("TMUS","TMUS"),("TSLA","TSLA"),("TTWO","TTWO"),
    ("TXN","TXN"),("UAL","UAL"),("ULTA","ULTA"),("VRSK","VRSK"),("VRSN","VRSN"),
    ("VRTX","VRTX"),("WBA","WBA"),("WDAY","WDAY"),("WDC","WDC"),("WLTW","WLTW"),
    ("WYNN","WYNN"),("XEL","XEL"),("XLNX","XLNX")])

    submit=SubmitField("Get Data")